services:
  server:
    image: myregistry.dataleapinfo.com:5443/dbgate-server:5.3.1
    init: true
    environment:
      - NODE_ENV=production
      - ENABLE_ONLINE=1
      - TRINO_URL=http://trion:8080
      - ONLINE_ADMIN_API=https://platform.dataleapinfo.com/dbapi
      - ONLINE_ADMIN_HOME=/db
      - ONLINE_DATABASE_URL=mysql://dbsun:@Sun12345@172.30.246.29:3306/smartdata
      - DB_URL=jdbc:mysql://172.30.246.29:3306/smartdata
      - DB_USER=dbsun
      - DB_PASSWORD_FILE=/run/secrets/db_password
      # redis sentinel
      # - REDIS_TYPE=sentinel
      # - REDIS_NAME=mymaster
      # - REDIS_SENTINELS=[{"host":"192.168.3.7","port":27001},{"host":"192.168.3.7","port":27002},{"host":"192.168.3.7","port":27003}]
      # - REDIS_PASSWORD=redis-123456
      # - REDIS_DB=0
      # redis single
      - REDIS_TYPE=none
      # - REDIS_PORT=6379
      # - REDIS_HOST=redis
      # - REDIS_PASSWORD=redis-123456
    secrets:
      - db_password
    networks:
      - dbserver
      - uccserver
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: '2g'
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.server.rule=PathPrefix(`/dbgatex/api`)'
        - 'traefik.http.routers.server.priority=10'
        - 'traefik.http.routers.server.service=server'
        - 'traefik.http.middlewares.api-stripPrefix.stripprefix.prefixes=/dbgatex/api'
        - 'traefik.http.routers.server.middlewares=api-stripPrefix'
        - 'traefik.http.services.server.loadbalancer.server.port=3000'
        - 'traefik.http.services.server.loadbalancer.sticky=true'
        - 'traefik.http.services.server.loadbalancer.sticky.cookie.name=dbgatex_cookie'
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider http://localhost:3000 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

secrets:
  db_password:
    external: true

networks:
  dbserver:
    external: true
  uccserver:
    external: true
