FROM node:20.12.2-alpine3.19 as base

WORKDIR /app

RUN apk --no-cache upgrade \
 && apk --no-cache add iputils \
 && apk add --no-cache python3 py3-pip && \
    rm -rf /var/cache/apk/*

COPY . .

RUN yarn install && yarn run prepare:docker

FROM base as production

WORKDIR /home/dbgate-docker

COPY ./docker .

RUN ["chmod", "+x", "/home/dbgate-docker/entrypoint.sh"]

EXPOSE 3000
VOLUME /root/.dbgate

CMD ["/home/dbgate-docker/entrypoint.sh"]
