FROM node:20.12.2-alpine3.19 as base

WORKDIR /app

RUN apk --no-cache upgrade \
 && apk --no-cache add  \
    iputils

COPY . .

RUN yarn run install && yarn run prepare:docker

FROM base as production

WORKDIR /home/dbgate-docker

COPY ./docker .

RUN ["chmod", "+x", "/home/dbgate-docker/entrypoint.sh"]

EXPOSE 3000
VOLUME /root/.dbgate

CMD ["/home/dbgate-docker/entrypoint.sh"]
