FROM 20.12.2-alpine3.19

WORKDIR /home/dbgate-docker

RUN apk --no-cache upgrade \
 && apk --no-cache add  \
    iputils

COPY . .

RUN ["chmod", "+x", "/home/dbgate-docker/entrypoint.sh"]

WORKDIR /home/dbgate-docker
EXPOSE 3000
VOLUME /root/.dbgate

CMD ["/home/dbgate-docker/entrypoint.sh"]
