services:
  server:
    image: myregistry.dataleapinfo.com:5443/dbgate:latest
    #image: dbgate:latest
    init: true
    environment:
      - ENABLE_ONLINE=1
      - ONLINE_ADMIN_API=https://platform.dataleapinfo.com/dbapi
      - ONLINE_ADMIN_HOME=https://platform.dataleapinfo.com/db
      - ONLINE_DATABASE_URL=mysql://dbsun:@Sun12345@8.134.215.8:3306/smartdata
    networks:
      - dbserver
    ports:
      - '3020:3000'
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ['CMD', 'node', '/home/dbgate-docker/healthcheck.js']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  dbserver:
    external: true
